name: Test PyPI Publish

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Test install
        run: |
          pip install dist/*.whl
          python -c "import earth; print(f'Earth version: {earth.__version__}')"

      - name: Test modular installs
        run: |
          pip install "dist/*.whl[companies]"
          pip install "dist/*.whl[campaigns]" 
          pip install "dist/*.whl[automotive]"
          pip install "dist/*.whl[all]"
